### ISSUE TITLE
Customize generator prefix

### ISSUE THREAD

**Issue by arichiardi** [seancorfield/clj-new#13]
Hi Sean,

Opening a new issue so that we can discuss how to approach the problem of customizing the prefix parameter to the generator - it looks like there is no way for a generator to tell what prefix to target and it seems like every change would be breaking so better talk about it beforehand.

The arguments to `-main` are a non-solution because we don't want the user to input the prefix, but the generator setting it.

I am tempted to propose a `new.generate2` command or a command that reads from a `clj.generate2.foo/generate2` function with completely different semantics.

I would like to restate my goal here as well: be able to have a mechanism to additively modify edn files in the project.

Thank you a lot again as usual.

P.S.: I can take care of the patch

**Comment by seancorfield** [comment]
This makes no sense: the generator is already passed `prefix`, the generator "argument", and any subsequent command line arguments. The generator can simply ignore the `prefix` or write to wherever it want so it is already totally in control of the `prefix`.

The right solution here is to make `clj-new` do argument parsing, probably with `tools.cli` (there's already an open ticket for this) so that _all_ of the Boot/clj generator arguments can be supplied and users have "total" control.

**Comment by arichiardi** [comment]
Hi Sean, can you explain me like I was five what you mean by total control to the user? I might be misunderstanding that piece.

I thought it was clear from the above that the user does not have anything to do with it. The generator should be in control of the files it targets.
It is true that a generator can just read/write anything basically, but are you really with what you described above? In terms of design and semantics I mean...the fact that the generator has to ignore one (hardcoded and unconfigurable) parameter it is at least a code-smell.

In any case, I think I will be rolling with whatever is available right now adding only that it seems a bit left there in the air, while the only think I am asking would be an improved design for something that I can contribute no problem.

**Comment by seancorfield** [comment]
Users can now specify `-p PATH` to provide a prefix path relative to the current directory. This is passed into the generator as the first argument -- which the generator may use or ignore as it sees fit. So the generator has control over whether to use the `prefix` or not. This allows a generator to be guided by the user or to make its own decision about what files to work on.

For any generator that wants to operate outside of the (default) `src` folder, my recommendation would be to check the `prefix` argument and, if it is `src`, let the user know it will modify files in the project root, else it should either respect the `prefix` (for example, if `"."` is specified) or else warn the user it will modify files elsewhere.

Given that you're asking for the ability for a generator to "do whatever it wants", I think it should let the user know what files it is updating if it isn't respecting the `src` folder!
