### ISSUE TITLE
The template template generates invalid namespaces by default

### ISSUE THREAD

**Issue by SevereOverfl0w** [seancorfield/clj-new#14]
If you create a project named "juxt/ginger" with the template generated by the template named template, your filesystem layout looks like:

`src/juxt/ginger/foo.clj`, but the namespace within is `ginger.foo`, missing the `juxt.` prefix.

I guess it should be updated to act like app? https://github.com/seancorfield/clj-new/blob/4c8b21e1d33d96784e386754d99708772f5ba6e5/src/clj/new/app.clj#L11

**Comment by seancorfield** [comment]
PR welcome. The template template needs a lot of love. It's not something that many people use.
