### ISSUE TITLE
Hard to conditionally add some files

### ISSUE THREAD

**Issue by SevereOverfl0w** [seancorfield/clj-new#15]
For example, I may only want to add sass files if the project has "--frontend" as a flag.

Currently to do this I have to create a second block lik.e:

```
(when frontend?
  (binding [*force?* true]
    (->files …)))
```

The `*force?*` in particular makes this awkward, as I don't know what other implications that has.

One option would be to have `->files` ignore `nil`, such that this would work:

```
(->files data
  ["main.clj" …]
  (when frontend?
    ["main.cljs …"]))
```

**Comment by seancorfield** [comment]
That sounds like a nice enhancement.

The `*force?*` stuff is intended just to control whether files are overwritten (just FYI).

**Comment by seancorfield** [comment]
I think it would be as simple as changing this line https://github.com/seancorfield/clj-new/blob/master/src/clj/new/templates.clj#L171 to be `(doseq [path (remove nil? paths)]` yes?

**Comment by seancorfield** [comment]
Feel free to try this out via a Git dep. It'll be in the next release if it works for you.
