### ISSUE TITLE
compojure template fails to create deps.edn

### ISSUE THREAD

**Issue by jr0cket** [seancorfield/clj-new#22]
Using the https://github.com/weavejester/compojure-template to create projects with clj-new fails to create a `deps.edn` file.

`clojure -A:new compojure practicalli/compojure-website`

This creates the following project files, but a `deps.edn` file is not created.
```
compojure-website-cli
├── project.clj
├── README.md
├── resources
│   └── public
├── src
│   └── practicalli
│       └── compojure_website
│           └── handler.clj
└── test
    └── practicalli
        └── compojure_website
            └── handler_test.clj
```

Using the multi-segment name the same files are produced, without the `deps.edn` file again

`clojure -A:new compojure practicalli.my-website `

Using the following leiningen command, the same project files are created and content in all files are identical.

`lein new compojure practicalli/compojure-website`

`clj-new` version 0.7.6 is used by adding an alias to the `$HOME/.clojure/deps.edn` file

```
 :aliases
 {:new {:extra-deps {seancorfield/clj-new
                     {:mvn/version "0.7.6"}}
        :main-opts  ["-m" "clj-new.create"]}}
```

**Comment by seancorfield** [comment]
`clj-new` just runs templates as-is. If the template doesn't produce a `deps.edn`, you need to petition the template maintainer to add that. It's not a function of `clj-new`.

**Comment by jr0cket** [comment]
Thank you for clarifying the purpose of clj-new.
