### ISSUE TITLE
More template examples

### ISSUE THREAD

**Issue by dijonkitchen** [seancorfield/clj-new#26]
Maybe provide a few examples for other templates like:
https://github.com/luminus-framework/luminus-template
and 
https://github.com/day8/re-frame-template

**Comment by dijonkitchen** [comment]
Thanks Sean! This helps clarify that it doesn't convert all existing templates to a deps.edn project.

**Comment by seancorfield** [comment]
Yup. It never occurred to me that anyone would expect that behavior until someone mentioned it to me on Slack a while back. Updating the README to explicitly state that, with some examples, was a good idea -- thank you!
