### ISSUE TITLE
clj -A:install fails for template on windows 10 in powershell

### ISSUE THREAD

**Issue by sveri** [seancorfield/clj-new#31]
Hi,

I just wanted to try clj new on W10 in the powershell. Creation of a template with: 
    clj -A:new template de.sveri/closp 
works and I can open it fine in cursive. However, when I want to install this project with:
    clj -A:install
I get a FileNotFoundException:

Execution error (FileNotFoundException) at java.io.FileInputStream/open0 (FileInputStream.java:-2).
  closp.jar (Das System kann die angegebene Datei nicht finden)
  
  {:clojure.main/message "Execution error (FileNotFoundException) at java.io.FileInputStream/open0 (FileInputStream.java:-2).\r\nclosp.jar (Das System kann die angegebene Datei nicht finden)\r\n", :clojure.main/triage {:clojure.error/class java.io.FileNotFoundException, :clojure.error/line -2, :clojure.error/cause "closp.jar (Das System kann die angegebene Datei nicht finden)", :clojure.error/symbol java.io.FileInputStream/open0, :clojure.error/source "FileInputStream.java", :clojure.error/phase :execution}, :clojure.main/trace {:via [{:type org.eclipse.aether.installation.InstallationException, :message "Failed to install artifact closp:clj-template:jar:0.1.0-SNAPSHOT: closp.jar (Das System kann die angegebene Datei nicht finden)", :at [org.eclipse.aether.internal.impl.DefaultInstaller install "DefaultInstaller.java" 280]} {:type java.io.FileNotFoundException, :message "closp.jar (Das System kann die angegebene Datei nicht finden)", :at [java.io.FileInputStream open0 "FileInputStream.java" -2]}], :trace [[java.io.FileInputStream open0 "FileInputStream.java" -2] [java.io.FileInputStream open "FileInputStream.java" 213] [java.io.FileInputStream <init> "FileInputStream.java" 155] [org.eclipse.aether.internal.impl.DefaultFileProcessor copy "DefaultFileProcessor.java" 162] [org.eclipse.aether.internal.impl.DefaultFileProcessor copy "DefaultFileProcessor.java" 150] [org.eclipse.aether.internal.impl.DefaultInstaller install "DefaultInstaller.java" 267] [org.eclipse.aether.internal.impl.DefaultInstaller install "DefaultInstaller.java" 195] [org.eclipse.aether.internal.impl.DefaultInstaller install "DefaultInstaller.java" 152] [org.eclipse.aether.internal.impl.DefaultRepositorySystem install "DefaultRepositorySystem.java" 377] [jdk.internal.reflect.NativeMethodAccessorImpl invoke0 "NativeMethodAccessorImpl.java" -2] [jdk.internal.reflect.NativeMethodAccessorImpl invoke "NativeMethodAccessorImpl.java" 62] [jdk.internal.reflect.DelegatingMethodAccessorImpl invoke "DelegatingMethodAccessorImpl.java" 43] [java.lang.reflect.Method invoke "Method.java" 567] [clojure.lang.Reflector invokeMatchingMethod "Reflector.java" 167] [clojure.lang.Reflector invokeInstanceMethod "Reflector.java" 102] [cemerick.pomegranate.aether$install_artifacts invokeStatic "aether.clj" 377] [cemerick.pomegranate.aether$install_artifacts doInvoke "aether.clj" 363] [clojure.lang.RestFn applyTo "RestFn.java" 137] [clojure.core$apply invokeStatic "core.clj" 665] [clojure.core$apply invoke "core.clj" 660] [cemerick.pomegranate.aether$install invokeStatic "aether.clj" 450] [cemerick.pomegranate.aether$install doInvoke "aether.clj" 436] [clojure.lang.RestFn invoke "RestFn.java" 619] [deps_deploy.deps_deploy$eval1602$fn__1604 invoke "deps_deploy.clj" 45] [clojure.lang.MultiFn invoke "MultiFn.java" 229] [deps_deploy.deps_deploy$_main invokeStatic "deps_deploy.clj" 52] [deps_deploy.deps_deploy$_main doInvoke "deps_deploy.clj" 51] [clojure.lang.RestFn invoke "RestFn.java" 425] [clojure.lang.AFn applyToHelper "AFn.java" 156] [clojure.lang.RestFn applyTo "RestFn.java" 132] [clojure.lang.Var applyTo "Var.java" 705] [clojure.core$apply invokeStatic "core.clj" 665] [clojure.main$main_opt invokeStatic "main.clj" 514] [clojure.main$main_opt invoke "main.clj" 510] [clojure.main$main invokeStatic "main.clj" 664] [clojure.main$main doInvoke "main.clj" 616] [clojure.lang.RestFn applyTo "RestFn.java" 137] [clojure.lang.Var applyTo "Var.java" 705] [clojure.main main "main.java" 40]], :cause "closp.jar (Das System kann die angegebene Datei nicht finden)"}}

**Comment by seancorfield** [comment]
You forgot to create the JAR file:
```bash
(! 1158)-> clj -A:new template de.sveri/closp
...
Generating a project called closp that is a 'clj-new' template
(! 1159)-> cd closp/
(! 1160)-> clj -A:jar
Building thin jar: closp.jar
Processing pom.xml for {closp/clj-template {:mvn/version "0.1.0-SNAPSHOT"}}
(! 1161)-> clj -A:install
...
Installing closp/clj-template-0.1.0-SNAPSHOT to your local `.m2`
done.
(! 1162)-> 
```
Per the `README` of the generated template project:
```
Build a deployable jar of this template:

    $ clojure -A:jar

Install it locally:

    $ clojure -A:install
```

**Comment by sveri** [comment]
Ah, nevermind. I did not create the jar before. I was not aware this was required. IIRC leiningen install just build the jar and installed it locally and I was accustomed to that workflow.
