### ISSUE TITLE
Generator ergonomics

### ISSUE THREAD

**Issue by dijonkitchen** [seancorfield/clj-new#36]
For the [generators](https://github.com/seancorfield/clj-new#clj-generators), maybe consider not automatically generating files within the `./src` directory. 

This allows one to use the terminal's autocompletion to quickly drill down into a deep namespace and make a new namespace. It seems like the file generator isn't really worth all the effort since you can just create that file easily in the terminal and just type the namespace declaration with less work and autocompletion natively. 

Currently, I can use autocompletion to do something like this, but it nests a new `./src/src` directory under the original `./src`. 
```sh
clj -m clj-new.generate ns=./src/clj/myname/myapp/somedomain/model/user
```
It properly appends `.clj` to the file and starts it off with the namespace declaration, but it is `/` seperated instead of `.`'s. 
```clj
(ns ./src/clj/myname/myapp/somedomain/model/user
  "Generated by clj")
```

**Comment by seancorfield** [comment]
Generators came from `boot-new` and have never had much effort invested in them. I probably need to rethink them substantially (or split them out into a separate project). I don't tend to use them because it's easier to just create/edit files in my editor.

**Comment by stathissideris** [comment]
Some less trivial use cases for generators if they're ever reworked:

- Adding the latest version of a dependency
- Adding part of a template to an existing project (the `+` options of templates - how do you ensure compatibility?)
- Adding a route+handler to a web API (with autodetect of routing/web server - this is veering into scifi territory, I know)
- Adding component/integrant/mount boilerplate for a new component

**Comment by seancorfield** [comment]
I think at this point I'm going to close this out since I'm really focusing on `deps-new` at this point and I think that code rewriting to update files should be a separate project -- and I'm not sure whether these should be CLI-based or part of refactoring support in an editor.

**Comment by dijonkitchen** [comment]
Cool! Link for those who don't know: https://github.com/seancorfield/deps-new
