### ISSUE TITLE
Any options for setting the repository gitlab.com instead of github?

### ISSUE THREAD

**Issue by matteoredaelli** [seancorfield/clj-new#44]
When I create a new project I always need to update pom.xml replacing github with gitlab.

Are there any options for setting the git repository/url?

Thanks in advance
Matteo

**Comment by seancorfield** [comment]
I'm not familiar with GitLab -- would anything else need changing in the URL other than replacing `github` with `gitlab`?

**Comment by matteoredaelli** [comment]
yes,
- the hostname is gitlab.com instead of github.com
- the path is like in github.

https://gitlab.com/USERNAME/REPOSITORYNAME

for instance

https://gitlab.com/matteoredaelli/matteoredaelli.gitlab.io

**Comment by seancorfield** [comment]
OK, I will add an `:scm-domain` "env" variable that can be set via the `-e` / `--env` option. That way you can set a default in your `~/.clojure/deps.edn` file for your `:new` alias and you will be able to override on the command-line.

Or if you're on the latest prerelease CLI, you could use the `-X` option and have an alias for creating github projects and another alias for creating gitlab projects, using `:exec-args` defaults.

**Comment by seancorfield** [comment]
You can try this on the **develop** branch with a `:git/url` / `:sha` dependency or you can wait until the next release.
