### ISSUE TITLE
Switch default group ID to com.github.<username>?

### ISSUE THREAD

**Issue by seancorfield** [seancorfield/clj-new#51]
We could assume that a project name like username/my-project should have a group ID of com.github.username instead of just plain username.

We could also accept (and encourage) a fully-qualified com.github.username/my-project name.

And then we could derive the SCM from such a reverse domain name? com.gitlab.username works.

What about com.acme/my-project (or com.acme.department/my-project)?

**Comment by seancorfield** [comment]
See https://github.com/clojars/clojars-web/wiki/Verified-Group-Names for the policy.

**Comment by seancorfield** [comment]
The changes I've made so far allow the following:
* myusername/myproject -- gets a group of `org.clojars.myusername` (new) and an artifact of `myproject`, and a primary namespace of `myusername.myproject`, with SCM assuming `https://github.com/myusername/myproject`
* com.github.myusername/myproject -- gets a group of `com.github.myusername` and an artifact of `myproject`, and a primary namespace of `myusername.myproject` (new), with SCM assuming `https://github.com/myusername/myproject` (a change from the previous assumption)
* com.acme/myproject -- gets a group of `com.acme` and an artifact of `myproject`, and a primary namespace of `com.acme.myproject`, with SCM assuming `https://github.com/com.acme/myproject`

For `com.github`, `io.github` is also accepted. For `com.gitlab` and `io.gitlab`, the SCM domain is assumed to be `gitlab.com` but otherwise the examples above still apply.

If a dotted project name is used, the same rules as before exist to derive a group and an artifact: my.username.project is treated as my.username/project for the most part but the primary namespace will be `my.username.project` and while the group is `my.username`, the artifact will be `my.username.project` (as before). Since `my.username` looks like a reversed domain name (`username.my`), it will be accepted as the group ID.

**Comment by tobias** [comment]
> myusername/myproject -- gets a group of org.clojars.myusername (new) and an artifact of myproject, and a primary namespace of myusername.myproject, with SCM assuming https://github.com/myusername/myproject

I would make this `net.clojars.myusername` instead of `org...` - the `org` groups have the connotation of being for sandbox/fork libraries (and Clojars will call them out in the UI as such on some pages) so I would like to steer folks to the new `net` groups for real libraries.

I didn't add `io.gitlab` to the plan, but see now that `gitlab.io` subdomains are used the same way as `github.io` ones, so I'll update the wiki page to reflect that.

**Comment by seancorfield** [comment]
@tobias Thank you. Updated that default to `net.clojars.username` if the group doesn't look like a reverse domain name.

**Comment by seancorfield** [comment]
This is mostly done at this point. #54 covers the open issue of template names.
