### ISSUE TITLE
polylith with multi segment namespaces

### ISSUE THREAD

**Issue by slifin** [seancorfield/clj-new#60]
I'm not sure if this is a bug but maybe an issue?

I used the following command to create a polylith project:
```
clojure -X:project/new :template polylith :name meetup/nl-clojure
```

Which successfully generated a project for me, then I did `poly info` inside that workspace and I get the following error:

```
The command can only be executed from the workspace root, or by also passing in :: or ws-dir:DIR.
```

My guess is that the multi segment namespace is maybe not lining up with what poly expects?

**Comment by seancorfield** [comment]
I cannot reproduce that, using `clj-new` 1.1.297 (I don't know what your `:project/new` alias is?):

```
(! 1230)-> clojure -X:new :template polylith :name meetup/nl-clojure
Generating a project called nl-clojure based on the 'polylith' template.
Initialized the project for use with 'git'.
(! 1231)-> cd nl-clojure/
(! 1232)-> clojure -M:poly info
  stable since: 1d7b460

  projects: 3   interfaces: 1
  bases:    1   components: 1

  project         alias  source
  -----------------------------
  nl-clojure      app     -x-  
  nl-clojure-lib  lib     ---  
  development     dev     x--  

  interface  brick     app  lib   dev
  ------------------   --------   ---
  greeter    greeter   xx-  xx-   xx-
  -          cli       xx-  ---   xx-
```

**Comment by seancorfield** [comment]
The created project should have these contents:

```
(! 1233)-> ls
CHANGELOG.md	README.md	components	development	workspace.edn
LICENSE		bases		deps.edn	projects
```

**Comment by slifin** [comment]
Oh sorry yeah the alias is from https://github.com/practicalli/clojure-deps-edn around here: https://github.com/practicalli/clojure-deps-edn/blob/0dc9ca790ed35479d126bf89b53cb6285d85de05/deps.edn#L234

<img width="1244" alt="Screenshot 2021-04-15 at 09 54 47" src="https://user-images.githubusercontent.com/198857/114842294-9f853e00-9dd0-11eb-988f-9bf093cbc117.png">

**Comment by seancorfield** [comment]
Ah, you're using the native `poly` command which is not tracking the `issue-66` branch in the Polylith repo.

Use `clojure -M:poly ...` inside the generated project. `clj-new` is tracking the `issue-66` branch and the structure of the generated project matches the _new structure_ that Polylith is using on that branch.

The native `poly` command is expecting the older project structure.

Per the `clj-new` README in the `polylith` template docs: "Generated projects currently track the [issue-66 branch of the poly tool](https://github.com/polyfy/polylith/tree/issue-66)."

The generated README in your new project links to that branch of the tool and says:

```
Get info about the workspace:

    $ clojure -M:poly info
```

I'll update the `clj-new` README section on `polylith` to make that clearer.

**Comment by seancorfield** [comment]
README updated. In the next `clj-new` release, the generated README in `polylith` projects will also make that clearer.
