### ISSUE TITLE
more explicit checks on clj-new cli parameters

### ISSUE THREAD

**Issue by behrica** [seancorfield/clj-new#79]
I still think "something" could be done to make clj-new more beginner friendly.

It is "very relaxed", regarding parameters

I can  type this:
```
clojure -X:project/new clj-new/create :template clj-py-r-template  :name me/my-app :blubblub aaaa
```

and it will ignore the extra, wrong parameters.

I know that this is partially Clojure tradition, but a "shell tool", ment for beginners as well, should maybe check for this.
(like most other tools in bash do)

**Comment by seancorfield** [comment]
I initially thought that additional key/value pairs were passed into the template itself -- per the help text(!) -- but it turns out that isn't true so I can spot "unknown" options here and complain about them.

**Comment by seancorfield** [comment]
```bash
(! 724)-> clojure -X:new :name foo/bar :blubblub aaa
Ignoring the following unknown (misspelled?) options:
* :blubblub aaa
...
```

It goes on and creates the project if there are no errors but at least it tells you what it is ignoring.
