### ISSUE TITLE
allow generators to add an alias/deps to deps.edn

### ISSUE THREAD

**Issue by bhauman** [seancorfield/clj-new#8]
Just putting this out there as food for thought.

Now that configuration is `just edn` we could use `rewrite-clj` and allow generators to update deps.edn.

The use case I have in mind is to be able to generate figwheel on an existing project.

This is of course challenging as it's extremely difficult for generators to compose, but if we scope all changes to an alias that is managed by a set of generators, it becomes more approachable.

**Comment by seancorfield** [comment]
Sounds good. PR welcome -- I haven't looked at `rewrite-clj` at all yet.

**Comment by arichiardi** [comment]
I think I had some similar requirement in having to add arbitrary pieces of data to configuration files in the project root, like adding a build to the `shadow-cljs.edn` file.

**Comment by bhauman** [comment]
I meant to close this since we can do arbitrary computation in the template code.

**Comment by arichiardi** [comment]
yep definitely, but approaching this in the generators would be I think better, the limitation here is just that only `src` is at the moment passed in.

**Comment by arichiardi** [comment]
@seancorfield any feedback on this latest idea, is it worth a separate issue and a soon-to-be PR? :smile:

**Comment by seancorfield** [comment]
I take part of my last comment: although the `prefix` argument passed into the generator is always `src` right now, the generator could simply ignore it and write to any files within the project. So neither aspect of this is appealing to me right now -- it just makes me more inclined to add full-blown command line argument parsing (maybe with `tools.cli`).

**Comment by arichiardi** [comment]
There is a problem with that approach, see other issue.
