### ISSUE TITLE
Misspelled template name results in hard to understand error message

### ISSUE THREAD

**Issue by behrica** [seancorfield/clj-new#80]
Doing this:

```
clojure -X:project/new clj-new/create :template clj-py-r-templateXX  :name me/my-app 
```
Gives me:

```
Failed with: Failed to resolve version for clj-py-r-templateXX:lein-template:jar:RELEASE: Could not find metadata clj-py-r-templateXX:lein-template/maven-metadata.xml in local (/home/carsten/.m2/repository)
Execution error (ExceptionInfo) at clj-new.helpers/resolve-remote-template (helpers.clj:171).
Could not load artifact for template: clj-py-r-templateXX
	Tried coordinates:
		[clj-py-r-templateXX/boot-template "RELEASE"]
		[clj-py-r-templateXX/lein-template "RELEASE"]

For more detail, enable verbose logging with :verbose 1, 2, or 3

```

which has 3 issues:

1. It talks about "lein template" and "boot template"  but I look for a clj-template. Did it check this as well ? it should at least tell me.
2. It says that the error is in my local repo:  Could not find metadata clj-py-r-templateXX:lein-template/maven-metadata.xml in **local** (/home/carsten/.m2/repository)
  -> What does it look in "local", if it does not find it on the server ? This "sounds" to me firstly like an issue with my local maven folder.
  3. It asks me to enable verbose logging, which I cannot really do, can I ?

I propose to reprase this exception and just tell the user:

"Template xxx for boot/lein/clj not found in remote repositories"

I see here https://github.com/seancorfield/clj-new/blob/0e65282b89c2b841a296210c028682b4f66d493c/src/clj_new/helpers.clj#L177

That you don't print the clj-template name in case of error. Any reason for this ?

**Comment by behrica** [comment]
I just see that ":verbose 3" would show me three 3 failed downloads, in a long trace.
So my point 3) is not valid.

**Comment by behrica** [comment]
So maybe just to add the "clj-template" nou found in line 177 would be a quick win.

And maybe use : Could not download artifact for template ...

I am not a native english speaker, but "load" could mean as well "load from locally", while the error is, that it can not be retrieved from remotely.

**Comment by seancorfield** [comment]
The exception referencing `local` comes from the underlying Maven libraries so I can't really do much about that -- but I could probably call it out differently.

I could definitely add the `clj-template` coordinates -- but bear in mind that those templates can also come from the classpath (where it would be "loaded") or from git coordinates or from a local directory (which the lein and boot versions can't).

I'll see what I can do about cleaning that up.

**Comment by seancorfield** [comment]
I'm going to change it to this:
```clojure
        (println "Failed with (underlying error, possibly from Maven):")
        (println "   " (.getMessage @failure) "\n")
        (throw (ex-info
                (format (str "Could not locate the artifact for template: %s\n"
                             "\tTried coordinates:\n"
                             "\t\t{%s %s}\n"
                             "\t\t[%s \"%s\"]\n"
                             "\t\t[%s \"%s\"]%s")
                        template-name
                        clj-tmp-name (pr-str clj-version)
                        boot-tmp-name tmp-version
                        lein-tmp-name tmp-version
                        (more-debugging))
                {}))))))
```

**Comment by seancorfield** [comment]
Example output now:
```bash
(! 726)-> clojure -X:create :template there-is-no-such-template :name foo/bar

Failed with (underlying error, possibly from Maven):
    Failed to resolve version for there-is-no-such-template:lein-template:jar:RELEASE: Could not find metadata there-is-no-such-template:lein-template/maven-metadata.xml in local (/Users/sean/.m2/repository) 

Execution error (ExceptionInfo) at clj-new.helpers/resolve-remote-template (helpers.clj:172).
Could not locate the artifact for template: there-is-no-such-template
	Tried coordinates:
		{there-is-no-such-template/clj-template #:mvn{:version "RELEASE"}}
		[there-is-no-such-template/boot-template "RELEASE"]
		[there-is-no-such-template/lein-template "RELEASE"]

For more detail, enable verbose logging with :verbose 1, 2, or 3
```
Note that it using the `deps.edn` format of coordinates for the `clj-template` so it will reflect git deps and local deps too.

**Comment by behrica** [comment]
> The exception referencing `local` comes from the underlying Maven libraries so I can't really do much about that -- but I could probably call it out differently.
> 
> I could definitely add the `clj-template` coordinates -- but bear in mind that those templates can also come from the classpath (where it would be "loaded") or from git coordinates or from a local directory (which the lein and boot versions can't).
> 
This for sure explains part of my confusion.
Why is a "template" different in this sense, then a usual dependency in deps.edn ?

If a usual clojure dependency  resolution / download"fails", there can only be one reason (apart from network hickups);
The deps is not in any of the specified remote repositories.
That it is locally cached is mostly irrelevant for the end user, apart from speed.

**Comment by seancorfield** [comment]
You can do a local install of a JAR to your `~/.m2/` repository and tooling will pick it up from there without downloading anything.

The `clj-template` can come from `:git/url` or `:local/root` dependencies because `tools.deps.alpha` supports that (the library behind `deps.edn`).

The `clj-template` can also just be on your classpath, brought in by other aliases, so it could easily be local code in your current project (this is particularly true for the generator side of `clj-new` and also for the newer, simpler `deps-new`). So it's possible that a template could be resolved just in the local execution context, without anything needing to be downloaded.
