### ISSUE TITLE
clj-new/create calls `(shutdown-agents)`

### ISSUE THREAD

**Issue by SevereOverfl0w** [seancorfield/clj-new#82]
This means I can't call the function `clj-new/create` as part of a test, and then run a future in the rest of my program.  I don't believe this is necessary any more, now that clj calls shutdown-agents for you.

**Comment by seancorfield** [comment]
That call is part of the `-M` path as well as the `-X` path so I think the best thing for me to do at this point to accommodate your use case is to move the `shutdown-agents` to a dynamic Var so you can wrap the call in `binding` to override it. How does that sound?

**Comment by seancorfield** [comment]
Check out that commit and see if that works for you? I haven't documented it yet (that whole ns is "not documented" so I'll have to figure out where to put the note about programmatic use of `create` and `generate`).

**Comment by SevereOverfl0w** [comment]
That should work for me, I worked around it initially by doing a `with-redefs`.

A better solution might be to move the call to `(shutdown-agents)` into `clj-new.generate/-main` though?

**Comment by seancorfield** [comment]
The CLI stopped calling `(shutdown-agents)` as of 1.10.3.933: https://github.com/clojure/brew-install/commit/71596a069e87d039ad3c1f923ad975f81e8052cc -- see https://clojure.atlassian.net/browse/TDEPS-198 for the background to part of that (esp. the linked "ask").

That means that if your "exec" function doesn't call `(shutdown-agents)`, it can "hang" for 60 seconds at exit.

**Comment by SevereOverfl0w** [comment]
I'm not sure if that's right, https://github.com/cognitect-labs/test-runner/commit/23771f4bee77d4e938b9bfa89031d2822b4e2622 test-runner removed the custom shutdown logic.  

https://github.com/clojure/brew-install/commit/71596a069e87d039ad3c1f923ad975f81e8052cc removed the use of shutdown-agents, because instead -X will now override the executor with one that makes all threads a daemon so the JVM immediately shuts down: https://github.com/clojure/brew-install/commit/71596a069e87d039ad3c1f923ad975f81e8052cc#diff-83b45bcf686e1bdb7a6cb7b487143b5e11d47445302d290397c51bc7d6e33e64R114-R116.

You can test this by creating a file like so:

```clojure
;; src/foo.clj
(ns foo)

(defn bar
  [{}]
  (future 10)
  (println 10))

(defn -main
  [& args]
  (bar nil))
```

Then running `clj -M -m foo` (which will hang) and comparing with `clj -X foo/bar` which won't!

**Comment by seancorfield** [comment]
I tested it with `clj-new` and some templates still create non-daemon threads and hang at the end.

**Comment by seancorfield** [comment]
That exit removal in Cognitect's `test-runner` was at least in part because we are using it programmatically at World Singles Networks and needed it to not call `System/exit` when tests failed!
