### ISSUE TITLE
Cannot find specific version of template

### ISSUE THREAD

**Issue by kjoshi** [seancorfield/clj-new#84]
Hello,
I'm trying to use clj-new to create a project using a specific version of the Luminus template so that I can follow-along with a tutorial.

I've installed clj-new as a tool:
`clojure -Ttools install com.github.seancorfield/clj-new '{:git/tag "v1.2.381"}' :as clj-new`

and then tried to create a new project:
`clojure -Tclj-new create :template luminus :version "3.91" :name kjoshi/example`

But I get the following error:
```
Failed with (underlying error, possibly from Maven):
    class java.lang.Double cannot be cast to class java.lang.CharSequence (java.lang.Double and java.lang.CharSequence are in module java.base of loader 'bootstrap')

Execution error (ExceptionInfo) at clj-new.helpers/resolve-remote-template (helpers.clj:176).
Could not locate the artifact for template: luminus
	Tried coordinates:
		{luminus/clj-template #:mvn{:version 3.91}}
		[luminus/boot-template "3.91"]
		[luminus/lein-template "3.91"]

For more detail, enable verbose logging with :verbose 1, 2, or 3
```

The version I've specified does seem to exist:
https://clojars.org/luminus/lein-template/versions/3.91

Not sure if I've just misunderstood how to use the `:version` option?
Thanks for your help

**Comment by seancorfield** [comment]
Are you on Windows? If so, please read the important section of the README that mentions quoting and links to the official Clojure CLI documentation about Windows and how to quote strings.

**Comment by kjoshi** [comment]
Sorry I should have mentioned, no I'm on macOS.

I managed to get it to work by adding extra single quotes around the version number:
`clojure -Tclj-new create :name kjoshi/example :template luminus :version '"3.91"'`
thanks fo the hint!

Is it expected the the command fails when no quotes are used around the version number at all?
I.e. `clojure -Tclj-new create :name kjoshi/example :template luminus :version 3.91` fails with the same error as above.

If so, would it be worth adding to the README that `:version` should be a quoted string?
E.g.
> `:version` -- use this specific version of the template

-> `:version` -- use this specific version of the template (as a [quoted](https://clojure.org/reference/deps_and_cli#quoting) string)

Thanks again for your help!

**Comment by seancorfield** [comment]
The CLI documentation is pretty clear about quoting strings. I am answering on my phone as I'm on vacation and missed that you hadn't quoted the string, sorry. When I get back, I can update the docs with an example of it is missing.

**Comment by seancorfield** [comment]
The README doesn't give an example of using `:version` for the template but I've added the following to the bullet point that lists the `:version` exec arg: 

> , e.g., `'"1.2.3"'` (remember that strings need to be 'quoted' as exec args)
