### ISSUE TITLE
Creating new re-frame project using example in readme creates an invalid symbol in the shadow-cljs.edn file

### ISSUE THREAD

**Issue by bpringe** [seancorfield/clj-new#87]
When I run this command from the readme (I know `yourname/spa` is meant to be replaced):

```
clojure -Tclj-new create :template re-frame :name yourname/spa :output front-end :args '[+garden "+10x" +routes]'
```

a project is created with this in the shadow-cljs.edn file at `[:builds :app :modules :app]`: `yourname/spa.core/init`, which is an invalid symbol. It should be `yourname.spa.core/init`.

I'm not sure if this is an issue with this library, or the template, or just my usage 😄.

**Comment by seancorfield** [comment]
Not all Leiningen templates are well-behaved when a qualified symbol is used as the project name. Sometimes you have to use a dotted-symbol instead:

```
clojure -Tclj-new create :template re-frame :name yourname.spa :output front-end :args '[+garden "+10x" +routes]'
```

produces:

```
   {:app {:init-fn yourname.spa.core/init}}
```

for that line.

You could open an issue about it on the `re-frame` template repo: https://github.com/day8/re-frame-template/issues

I'll update the `clj-new` README to use `yourname.spa` in that example and explain why `yourname/spa` won't work.

**Comment by seancorfield** [comment]
README updated. Caveat added to use of `lein`/`boot` templates.

**Comment by bpringe** [comment]
Thanks!
